name:               globus
version:            0.1.3
synopsis:           Globus Data Transfer
homepage:           https://github.com/DKISTDC/globus.hs
license:            BSD-3-Clause
author:             Sean Hess
maintainer:         shess@nso.edu
category:           System, Data, Science

extra-doc-files:
  - README.md

language: GHC2021

ghc-options:
  - -Wall

default-extensions:
  - TypeFamilies
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - DuplicateRecordFields
  - LambdaCase
  - NoFieldSelectors
  - StrictData

dependencies:
  - base >=4.16.4.0 && <5
  - aeson >= 2 && < 2.3
  - bytestring >= 0.11 && < 0.13
  - text >= 2 && <3
  - tagged >= 0.8 && < 0.9
  - effectful >= 2.3 && <3
  - exceptions
  - http-types >= 0.12 && < 0.13
  - http-api-data >= 0.6 && < 0.7
  - filepath
  - network-uri
  - http-client
  - http-client-tls





library:
  source-dirs: src


# tests:
#   tests:
#     main:        Main.hs
#     source-dirs: test/
#     dependencies:
#       - globus
#
